controllers:
    resource: ../src/Controller/
    type: attribute
chatbot_home:
    path: /chatbot
    controller: App\Controller\ChatBotController::index

chatbot_ask:
    path: /chatbot/ask
    controller: App\Controller\ChatBotController::ask
    methods: ['POST']
    # config/routes.yaml
feedbacks:
  resource: '../src/Controller/FeedbackController.php'
  type: annotation

