parameters:
    packs_images_directory: '%kernel.project_dir%/public/uploads/packs'
    google_api_key: 'AIzaSyDpxgIqCekHbOLgUL6fyHdavfAGr1KijcQ'
    video_directory: '%kernel.project_dir%/public/uploads/videos'
    evenement_images_directory: '%kernel.project_dir%/public/uploads/evenements'
    huggingface_api_key: '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'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $geminiApiKey: '%google_api_key%'

    App\Service\SentimentAnalysisService:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%huggingface_api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
