parameters:
            packs_images_directory: '%kernel.project_dir%/public/uploads/packs'
    google_api_key: 'AIzaSyDpxgIqCekHbOLgUL6fyHdavfAGr1KijcQ'
    video_directory: '%kernel.project_dir%/public/uploads/videos'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $geminiApiKey: '%google_api_key%'  # Liaison globale pour les arguments string nommés $geminiApiKey

    App\Service\BadWordsFilterService: ~
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
