# !!!
# 11/06/2025 Koussay : All API keys have been revoked and removed from this file, any key found in older commits will also not work ###
# !!!

parameters:
    packs_images_directory: '%kernel.project_dir%/public/uploads/packs'
    google_api_key: ''
    video_directory: '%kernel.project_dir%/public/uploads/videos'
    evenement_images_directory: '%kernel.project_dir%/public/uploads/evenements'
    voyages_images_directory: '%kernel.project_dir%/public/uploads/voyages'
    destinations_images_directory: '%kernel.project_dir%/public/uploads/destinations'
    audio_directory: '%kernel.project_dir%/public/uploads/audio'
    huggingface_api_key: ''
    app.admin_phone: ''
    app.low_stock_threshold: 10

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $geminiApiKey: '%google_api_key%'

    App\Controller\PaymentController:
        arguments:
            $logger: '@monolog.logger.payment'

    App\Service\SentimentAnalysisService:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%huggingface_api_key%'

    _instanceof:
        App\Service\CurrencyConverter:
            bind:
                $exchangeRateApiKey: ''

    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/AdvancedPaginationBundle/'
            - '../src/Kernel.php'

    App\Controller\ClientController:
        arguments:
            $passwordHasher: '@security.user_password_hasher'

    App\Service\EmailService:
        class: App\Service\EmailService
        arguments:
            $mailer: '@mailer'

    App\Service\TwilioSmsService:
        arguments:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioNumber: '%env(TWILIO_PHONE_NUMBER)%'
            $logger: '@logger'

    App\Controller\AudioController:
        arguments:
            $audioDirectory: '%audio_directory%'

    App\Service\HuggingFaceService:
        arguments:
            $apiKey: '%env(HUGGINGFACE_API_KEY)%'
            $model: '%env(HUGGINGFACE_MODEL)%'

    App\Service\StockMonitor:
        arguments:
            $smsService: '@App\Service\TwilioSmsService'
            $adminPhone: '%env(ADMIN_PHONE)%'

    App\Service\BadWordsFilterService:
        arguments:
            $geminiApiKey: '%google_api_key%'